name: 'PR self merge reward'
description: 'Posts a meme if someone merges their own PR'
author: 'Alin Stefan Olaru'
branding:
    icon: 'briefcase'  
    color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile
