name: 'Reward for own PR approval'
description: 'Posts a meme if someone approves/merges their own PR'
author: 'Alin Stefan Olaru'
branding:
    icon: 'briefcase'  
    color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile
